### ISSUE TITLE
develop branch does not build on Linux gcc 4.6

### ISSUE THREAD

**Issue by kalectro** [OpenNI/OpenNI2#10]
The master compiles but the develop branch gives me a lot of multiple definitions

```
In function `xnOSCountFiles': 
XnLinuxFiles.cpp:(.text+0x0): multiple definition of `xnOSCountFiles'
../../ThirdParty/PSCommon/XnLib/Bin/x64-Release/libXnLib.a(XnLinuxFiles.o):XnLinuxFiles.cpp:(.text+0x0): first defined here
../../ThirdParty/PSCommon/XnLib/Bin/x64-Release/libXnLib.a(XnLinuxFiles.o): In function `xnOSGetFileList':
XnLinuxFiles.cpp:(.text+0x60): multiple definition of `xnOSGetFileList'
../../ThirdParty/PSCommon/XnLib/Bin/x64-Release/libXnLib.a(XnLinuxFiles.o):XnLinuxFiles.cpp:(.text+0x60): first defined here
../../ThirdParty/PSCommon/XnLib/Bin/x64-Release/libXnLib.a(XnLinuxFiles.o): In function `xnOSOpenFile':
XnLinuxFiles.cpp:(.text+0x180): multiple definition of `xnOSOpenFile'
../../ThirdParty/PSCommon/XnLib/Bin/x64-Release/libXnLib.a(XnLinuxFiles.o):XnLinuxFiles.cpp:(.text+0x180): first defined here
```

**Comment by kalectro** [comment]
sorry... build artifacts...it worlks
