### ISSUE TITLE
Compile issues on Debian 6

### ISSUE THREAD

**Issue by Breakthru** [OpenNI/OpenNI2#11]
Hi,
I' m having some compile error for branch master on Debian 6 x86

g++ -MD -MP -MT "./../../../Bin/Intermediate/x86-Release/libPS1080.so/XnDepthStream.d ../../../Bin/Intermediate/x86-Release/libPS1080.so/XnDepthStream.o" -c -msse3 -Wall -O2 -DNDEBUG -I. -IInclude -I../../../Include -I../../../ThirdParty/PSCommon/XnLib/Include  -fPIC -fvisibility=hidden -o ../../../Bin/Intermediate/x86-Release/libPS1080.so/XnDepthStream.o DDK/XnDepthStream.cpp
In file included from ./DDK/XnFrameBufferManager.h:29,
                 from ./DDK/XnFrameStream.h:28,
                 from ./DDK/XnPixelStream.h:27,
                 from DDK/XnDepthStream.h:27,
                 from DDK/XnDepthStream.cpp:24:
./DDK/XnOniFramePool.h: In constructor ‘XnOniFramePool::XnOniFramePool()’:
./DDK/XnOniFramePool.h:45: error: class ‘XnOniFramePool’ does not have any field named ‘Pool’
./DDK/XnOniFramePool.h: In member function ‘virtual XnStatus XnOniFramePool::Release(OniFrame_)’:
./DDK/XnOniFramePool.h:61: error: ‘Pool’ has not been declared
In file included from ./DDK/XnFrameStream.h:28,
                 from ./DDK/XnPixelStream.h:27,
                 from DDK/XnDepthStream.h:27,
                 from DDK/XnDepthStream.cpp:24:
./DDK/XnFrameBufferManager.h: At global scope:
./DDK/XnFrameBufferManager.h:71: error: type ‘xnl::EventXnFrameBufferManager::NewFrameEventArgs’ is not derived from type ‘XnFrameBufferManager’
./DDK/XnFrameBufferManager.h:71: error: expected ‘;’ before ‘&’ token
./DDK/XnFrameBufferManager.h:73: error: expected ‘;’ before ‘private’
make[1]: *_\* [../../../Bin/Intermediate/x86-Release/libPS1080.so/XnDepthStream.o] Error 1

I'm using gcc 4.4.7

Anyone else had those errors?

Thanks

**Comment by MasWag** [comment]
Hi,
I'm having the same compile error on Vine Linux 6 x86
I'm using gcc 4.4.5

Thanks

**Comment by dankegel** [comment]
Compiles ok on Ubuntu 12.04 with gcc-4.6.3, but I get same errors as you on Ubuntu 10.04 with gcc-4.4.3

gcc bug?

**Comment by dankegel** [comment]
Yes, seems like a gcc problem.  The patch 
http://kegel.com/linux/openni2-gcc44.patch
seems to let it compile, but I have not yet used it in the real world.

**Comment by MasWag** [comment]
I'm using this patch 
https://github.com/OpenNI/OpenNI2/pull/16
and it seems to work well.

**Comment by dankegel** [comment]
Oh, good.  That's identical to my patch.

**Comment by dankegel** [comment]
As of OpenNI2-2.0.0.30, I use
https://gist.github.com/dankegel/6709225
for the "is not derived from type" errors.

**Comment by caiosba** [comment]
I can confirm I can compile it using g++-4.6 but can't compile using g++-4.4 (Ubuntu 12.04).
